sudo: false
language: python
matrix:
  include:
    - python: "3.5"
      env: LTD_MASON_BUILD=true
install:
  - pip install -r requirements.txt
  - pip install "ltd-mason>=0.2,<0.3"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd-mason-travis --html-dir _build/html
env:
  global:
    - LTD_MASON_BUILD=false  # disable builds in regular text matrix
    - LTD_MASON_PRODUCT="dmtn-035"
    - secure: "NMr1WwRzwrfXa5dWo4TSleFC3ZIOOe2PSGcAl/ZoQ0FypbA4KGFIwPnE/XlQ/DanWDsCS6H8UnHXaKRKCEMdADDYEfGL/9C7ATQ6dqCpJy5GtfXxaOIDZ+OLaS+IPv8110Gpnel8orpZ0NbYE07zIkn5lJJihtpUFiClouDZxJ/dPAXyg+5oFfXG9UeRjgnVsY8F/3F1rF/g3H152Op1D2Ct3zYVfDq1W68+nLSFd34JPlmwgOD/Rxux1//mQWIrGzYkE0/hY4eCOM3HBRDu7ET4k7l64+58l/RoavJS/+RIu/5E+UyThEcHxnUvYl1PJrw70twKMUWUAnI4y4BXDVunw4Fb4ebS8wr1FCwHxwRvsQrL9dKKcRLZZ6OQCFLmLfKGVMtLt8xLSX20TfLcMs7i7ETnXjbz9wwhwh/QjKPR84e4PzyQxOzi2/Pn8uT6+v9a9uYBbL1Vspuvc+EVoyJQGoE60699Gb1pfkYOUB5jAhDAqEMIWiQML9EhJURyyDGVfKoajX9O17L5gr55v1p2tTFRpwl5/k48U9g3YC2mpug9p69+3//gtzq9MzTJDCiAE3aLItEzAXpFoDazX37L7qmxI53DswTLb2OOG48vYnoe0YyJDgtIsD/1fsrFccjGFIgfC1G2xnkBHrAquksVPqpXB+vSiDhnyDoGKhw="
    - secure: "NGTjlruexIUF14VTzI5fWIKZ5G7ngPrWncCkEscK7g8Tb81YX/7e5zXQBk73BDnI5ZsfIBa4GmcGRQMIh46Ly+C+Th/StFDePAGW/fFwGSqNgDJW3JcbbLLBxVBEyjVTnrOMgTKq/y7fLVeM9u0y/crHhUmEMfETKUS+r5v84YmQPIKwwVLHxHdOSgmQcV0ehPsgvfMU/kyr/3xhocY0mRxAIe2a9TcWNr4IdAQx0AaqzEqj8z4hwn7ssrNs8GqsFEv+CEcKyvKaaBzQtLH5/wZKt1wT/klg7ZgIm04ukyLtDqCetjSRDVQMVlmGzBtlXtaSxI5RgS5i+GBspmq6opxlAyrrTNIo50+KHyJcApynGF8usqMxf71Qp/6kYwvJAJLmdQYQNM6GQZb4D2wFT6J8JyalHB6aLLCGFa4zUVP0jVCK+FHNjCD1W3JbGPOpW5evS/lolP137i9VEiKBl/TxNKbeyNJf3mt4GQTxS/xL5hRdoMLzFw8E7gqQDALaT+zxBZ3udhKnUwabbyd07RkHUGnKulIzNoLum310GGvfio/WCcKnskd0HN6ScMwBZNVB7nts4dQLWtqhMjmuJanZK7aVMXhx7XFZymw4btxMVVaYvRrKYycWu3Uhik5135qrYv6ZaOaspV2m6apOWdtkLTgIGuex98Axm32zMjQ="
